services:
  moto-server:
    image: motoserver/moto

  pulumi-provisioning:
    image: pulumi/pulumi
    depends_on:
      - moto-server
    environment:
      AWS_ACCESS_KEY_ID: moto_access_key
      AWS_SECRET_ACCESS_KEY: moto_secret_key
      AWS_REGION: us-east-1
      # https://www.pulumi.com/docs/concepts/state/#local-filesystem
      PULUMI_BACKEND_URL: file://~
      PULUMI_CONFIG_PASSPHRASE: changeMe
    volumes:
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./index.js:/tmp/index.js
      - ./backend.js:/tmp/backend.js
    entrypoint: >
      sh -c "/app/docker-entrypoint.sh"

